# Generated by Django 5.0 on 2024-10-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallah', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='created_at',
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(default=5, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(),
        ),
    ]
